apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azurahaven-backend-es
  namespace: demo-app
spec:
  refreshInterval: "1h" # Tự động sync phục vụ cho Secrets Rotation
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: azurahaven-prod-secret # Tên K8s Secret sẽ tạo ra cho App sử dụng
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: production/azurahaven/backend