apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: database-app
  namespace: argocd

spec:
  project: default
  source:
    repo: https://github.com/Nhandc9v/nhannguyen-aws-accelerator-p2.git
    targetRevision: HEAD
    path: w9/day-a/k8s-manifest/database

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true