# apiVersion: argoproj.io/v1alpha1
# kind: Application

# metadata:
#   name: database-app
#   namespace: argocd

# spec:
#   project: default
#   source:
#     repoURL: https://github.com/Nhande9v/nhannguyen-aws-accelerator-p2.git
#     targetRevision: main
#     path: cloud/w9/day-a/k8s-manifests/database

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: apps

#   syncPolicy: 
#     automated: 
#       prune: true
#       selfHeal: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nhande9v/nhannguyen-aws-accelerator-p2.git
    targetRevision: main
  path: cloud/w9/day-a/k8s-manifests/database # LỖI 1: Thụt lề sai (dòng này phải lùi vào trong thuộc về 'source')
  
  # LỖI 2: Dưới đây cố tình gõ sai từ khóa chính tả của Kubernetes/ArgoCD
  đích_đến_hạ_tầng: 
    server-he-thong: https://kubernetes.default.svc
    ten-namespace-viet-sai: apps