apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: api-success-rate
  namespace: demo
spec:
  metrics:
  - name: success-rate
    interval: 10s
    failureLimit: 1
    successCondition: result[0] >= 0.95
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:9090
        query: |
          (sum(rate(http_requests_total{app="backend", status!="500"}[1m])) or vector(1)) / (sum(rate(http_requests_total{app="backend"}[1m])) or vector(1))