apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:20-alpine
        command: ["node", "-e"]
        args:
          - |
            const http = require('http');
            http.createServer((req, res) => {
              res.writeHead(200, {'Content-Type': 'application/json'});
              res.end(JSON.stringify({ message: "Hello from Node.js Backend!", pod: process.env.HOSTNAME }));
            }).listen(8080);
        ports:
        - containerPort: 8080
  strategy:
    canary:
      analysis:
        templates:
        - templateName: api-success-rate # Kết nối tới file AnalysisTemplate
      steps:
      - setWeight: 20
      - pause: {duration: 1m} # Chạy 20% traffic trong 1 phút để kiểm tra
      - setWeight: 50
      - pause: {duration: 1m} # Chạy 50% traffic trong 1 phút
      - setWeight: 100