apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: frontend:apps/Deployment:demo/frontend
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"frontend:apps/Deployment:demo/frontend"},"name":"frontend","namespace":"demo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"frontend"}},"template":{"metadata":{"labels":{"app":"frontend"}},"readinessProbe":{"initialDelaySeconds":5,"periodSeconds":10,"tcpSocket":{"port":3000}},"spec":{"containers":[{"args":["const http = require('http');\nhttp.createServer((req, res) =\u003e {\n  // Gọi tới backend thông qua Service nội bộ của K8s\n  http.get('http://backend-service:8080', (beRes) =\u003e {\n    let data = '';\n    beRes.on('data', (chunk) =\u003e data += chunk);\n    beRes.on('end', () =\u003e {\n      res.writeHead(200, {'Content-Type': 'application/json'});\n      res.end(data); // Trả kết quả từ Backend về trình duyệt\n    });\n  }).on('error', (err) =\u003e {\n    res.end('Backend not reachable');\n  });\n}).listen(3000);\n"],"command":["node","-e"],"image":"node:20-alpine","name":"frontend"}]}}}}
  creationTimestamp: "2026-06-11T07:08:07Z"
  generation: 3
  name: frontend
  namespace: demo
  resourceVersion: "13043"
  uid: 70b6f3ca-3b40-4c5c-b1f3-737a60628f64
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - args:
        - |
          const http = require('http');
          http.createServer((req, res) => {
            // Gọi tới backend thông qua Service nội bộ của K8s
            http.get('http://backend-service:8080', (beRes) => {
              let data = '';
              beRes.on('data', (chunk) => data += chunk);
              beRes.on('end', () => {
                res.writeHead(200, {'Content-Type': 'application/json'});
                res.end(data); // Trả kết quả từ Backend về trình duyệt
              });
            }).on('error', (err) => {
              res.end('Backend not reachable');
            });
          }).listen(3000);
        command:
        - node
        - -e
        image: node:20-alpine
        imagePullPolicy: IfNotPresent
        name: frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-06-11T07:10:18Z"
    lastUpdateTime: "2026-06-11T07:10:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-11T07:08:07Z"
    lastUpdateTime: "2026-06-11T07:17:10Z"
    message: ReplicaSet "frontend-7bb986c448" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
