apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 2 # number of the pod
  selector: # The pod selector determining what pods the RC is operating on
    app: web-app # label value
  template: # pod template
    metadata:
      labels:
        app: web-app # label value
    spec:
      containers:          
      - name: nginx-container   
        image: nginx:latest     
        ports:
        - containerPort: 80     
        livenessProbe:          
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10