apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nhande9v/nhannguyen-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/gitops/k8s/observability 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

