apiVersion:  argoproj.io/v1alpha1
kind: Application

metadata:
  name: root-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/Nhandc9v/nhannguyen-aws-accelerator-p2.git
    targetRevision: main
    path: w9/day-a/gitops-root/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true