apiVersion: v1
kind: Service
metadata:
  name: azurahaven-backend-svc
  namespace: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: azurahaven-backend
  type: ClusterIP