apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: day-c-canary
  labels:
    release: prometheus # Label này phải trùng với Prometheus Operator Selector của bạn
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 10s