apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes-global-binding
subjects:
- kind: ServiceAccount
  name: pod-viewer-sa
  namespace: lab-rbac-policy
roleRef:
  kind: ClusterRole
  name: cluster-node-reader
  apiGroup: rbac.authorization.k8s.io