apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: lab-rbac-policy
rules:
  - apiGroups: [""] # "" biểu thị core API group
    resources: ["pods"]
    verbs:
      - get
      - list
      - watch
    