apiVersion: v1
kind: Service
metadata:
  name: backend-stable
  namespace: day-c-canary
  labels:
    app: backend
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: backend